name = "vinet-whatsapp-worker"
main = "src/index.js"
compatibility_date = "2024-06-01"

[assets]
#[[directory = "./public/"]]
#[[run_worker_first = true]]

[[d1_databases]]
binding = "DB"
database_name = "vinet-whatsapp-db"
database_id = "2e1228d6-b6f6-494e-b4de-9cdd508854a0"

[vars]
PHONE_NUMBER_ID = "104043025887306"
WHATSAPP_TOKEN = "EAALpZCXUFpXsBO9tCyAuJUdO9MObRocFxZAZCJlxheOZBNp8CTvDn1Was9K48VkK3G3QZADZCYKur24nnXe9FNmwaCuttnzgOezJQi9tZApBZCVaq9ZCsID3FxlvJb6E1p7uLZADEtNoRRpiLGL3UCCY0ZBVp4YxxZC7TL3iIGvaqDH6hwQbZAIToVJeVceeAQjEkyxQZD"
VERIFY_TOKEN = "vinet-whatsapp"
OPENAI_API_KEY = "REPLACE_THIS"
